export const SET_LEAGUE_NAME = 'SET_LEAGUE_NAME'
export const ADD_FAVORITE_TEAM = 'ADD_FAVORITE_TEAM'
export const SET_STATE_FAVORITE = 'SET_STATE_FAVORITE'
export const IS_FAVORITE_TEAM = 'IS_FAVORITE_TEAM'

export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'